name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update OpenSSL
      run: |
        sudo apt-get update
        sudo apt-get install --only-upgrade openssl

    - name: Set Environment Variable
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: 0
      run: echo "NODE_TLS_REJECT_UNAUTHORIZED is set to $NODE_TLS_REJECT_UNAUTHORIZED"

    - name: Use Node.js ${{ matrix.node-version }} in 'client' directory
      run: |
        cd client
        npm install
        npm run build --if-present
        npm test
      shell: bash

    - name: Use Node.js ${{ matrix.node-version }} in 'server' directory
      run: |
        cd server
        npm install
        npm run build --if-present
        npm test
      shell: bash
