on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy code to test repository
        run: |
          git clone https://github.com/Tanya-DSU/ODOP
          cd ODOP
          git archive --format=zip HEAD -o code.zip
          git clone https://github.com/Tanya-DSU/ODOP-Test
          cd ODOP-Test
          unzip ../ODOP/code.zip
          git add .
          git commit -m "Copied code from dev repository"
          git push
